Create .gitignore
UptakeOpenSource/updraft pull request #22
Opened 2018-10-11 21:17 UTC by zaynaib

Created a gitignore file. Are there any paths or files your team want to be ignored?

2018-10-11 21:24 UTC, jameslamb commented
Hey @zaynaib thanks for doing this!

If you're not sure where to start, I think this is a good set for an R project:

```
# R stuff
*.Rhistory
*.Rproj
*.rda
*.rds
*.Rdata

# data files
*.csv
**/*.csv
**/*.xlsx
**/*.pdf

# other misc stuff
*.DS_Store
```

2018-10-11 21:25 UTC, jameslamb requested changes
Can you please add the defaults I suggested? Then we will merge this up!

2018-10-11 21:26 UTC, jameslamb commented on .gitignore
> +# This a file which Git has been explicitly told to ignore
can you change this text? It's not actually that Git ignores _this file_.

Recommendation:

```
# This is a file telling Git what other files to ignore
```

2018-10-11 23:24 UTC, zaynaib commented on .gitignore
> +# This a file which Git has been explicitly told to ignore
Got it. Sorry for the grammar issues.

2018-10-12 04:46 UTC, jameslamb commented
Great thanks! Don't worry about the failing Travis stuff...totally unrelated to your code.

@cwschultz88 from my perspective, this PR is good to go.

@zaynaib We really appreciate you making this contribution and hope you'll come back to make more!

2018-10-12 04:46 UTC, jameslamb approved these changes

2018-10-12 20:29 UTC, zaynaib commented
@jameslamb Two questions. 1.) Do you know of any resources where I can about vignette with R?
2.) Is there anything else you need me to do for this PR? Or any other issues you need help with?

2018-10-13 21:53 UTC, jameslamb commented
@zaynaib Nothing else needed for this particular PR! @cwschultz88 is the maintainer so he'll be the one to merge this.

If you're interested in learning about vignettes in R packages, Hadley's book is a great resource: http://r-pkgs.had.co.nz/vignettes.html

If you're looking for other issues to pick up, check out [pkgnet!](https://github.com/UptakeOpenSource/pkgnet/issues). We have quite a few open issues, and perhaps looking through the code you'll find more. Any contributions are welcomed!

2018-10-19 03:10 UTC, cwschultz88 commented
Everything looks great -- thanks for the contribution!

2018-10-19 03:10 UTC, merged